// Legacy WordPress tag slugs preserved for SEO continuity.
export const LEGACY_TAGS: Record<string, string> = {
  "chlorine": "Chlorine",
  "cleaners": "Cleaners",
  "cleaning-pool": "Cleaning Pool",
  "cleaning": "Cleaning",
  "florida-pools": "Florida Pools",
  "home-pool": "Home Pool",
  "juno-beach": "Juno Beach",
  "jupiter-fl": "Jupiter, FL",
  "jupiter-pool-cleaners": "Jupiter Pool Cleaners",
  "jupiter-pool-company": "Jupiter Pool Company",
  "jupiter": "Jupiter",
  "north-palm-beach-pools": "North Palm Beach Pools",
  "north-palm-beach": "North Palm Beach",
  "palm-beach-gardens-fl": "Palm Beach Gardens, FL",
  "palm-beach-gardens-pool-service": "Palm Beach Gardens Pool Service",
  "palm-beach-gardens": "Palm Beach Gardens",
  "pool-cleaning-service-florida": "Pool Cleaning Service Florida",
  "pool-cleaning-service": "Pool Cleaning Service",
  "pool-maintenance-palm-beach-gardens-fl": "Pool Maintenance Palm Beach Gardens, FL",
  "pool-maintenance": "Pool Maintenance",
  "pool-service-palm-beach-gardens-fl": "Pool Service Palm Beach Gardens, FL",
  "pool-service": "Pool Service",
  "pools-service": "Pools Service",
  "pools": "Pools",
  "quality": "Quality",
  "skim-pools": "Skim Pools",
  "south-florida-pool-service": "South Florida Pool Service",
  "swimming-pool-home": "Swimming Pool Home",
  "swimming-pool": "Swimming Pool",
};
