/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoolServicePalmBeachGardensRouteImport } from './routes/pool-service-palm-beach-gardens'
import { Route as ContactGardensPoolServiceRouteImport } from './routes/contact-gardens-pool-service'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AboutGardensPoolServiceRouteImport } from './routes/about-gardens-pool-service'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolServicePalmBeachGardensRoute =
  PoolServicePalmBeachGardensRouteImport.update({
    id: '/pool-service-palm-beach-gardens',
    path: '/pool-service-palm-beach-gardens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactGardensPoolServiceRoute =
  ContactGardensPoolServiceRouteImport.update({
    id: '/contact-gardens-pool-service',
    path: '/contact-gardens-pool-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGardensPoolServiceRoute = AboutGardensPoolServiceRouteImport.update({
  id: '/about-gardens-pool-service',
  path: '/about-gardens-pool-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about-gardens-pool-service': typeof AboutGardensPoolServiceRoute
  '/author': typeof AuthorRoute
  '/contact-gardens-pool-service': typeof ContactGardensPoolServiceRoute
  '/pool-service-palm-beach-gardens': typeof PoolServicePalmBeachGardensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/tag/$tag': typeof TagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about-gardens-pool-service': typeof AboutGardensPoolServiceRoute
  '/author': typeof AuthorRoute
  '/contact-gardens-pool-service': typeof ContactGardensPoolServiceRoute
  '/pool-service-palm-beach-gardens': typeof PoolServicePalmBeachGardensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/tag/$tag': typeof TagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about-gardens-pool-service': typeof AboutGardensPoolServiceRoute
  '/author': typeof AuthorRoute
  '/contact-gardens-pool-service': typeof ContactGardensPoolServiceRoute
  '/pool-service-palm-beach-gardens': typeof PoolServicePalmBeachGardensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/tag/$tag': typeof TagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/about-gardens-pool-service'
    | '/author'
    | '/contact-gardens-pool-service'
    | '/pool-service-palm-beach-gardens'
    | '/sitemap.xml'
    | '/$category/$slug'
    | '/category/$category'
    | '/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/about-gardens-pool-service'
    | '/author'
    | '/contact-gardens-pool-service'
    | '/pool-service-palm-beach-gardens'
    | '/sitemap.xml'
    | '/$category/$slug'
    | '/category/$category'
    | '/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/about-gardens-pool-service'
    | '/author'
    | '/contact-gardens-pool-service'
    | '/pool-service-palm-beach-gardens'
    | '/sitemap.xml'
    | '/$category/$slug'
    | '/category/$category'
    | '/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  AboutGardensPoolServiceRoute: typeof AboutGardensPoolServiceRoute
  AuthorRoute: typeof AuthorRoute
  ContactGardensPoolServiceRoute: typeof ContactGardensPoolServiceRoute
  PoolServicePalmBeachGardensRoute: typeof PoolServicePalmBeachGardensRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  TagTagRoute: typeof TagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-service-palm-beach-gardens': {
      id: '/pool-service-palm-beach-gardens'
      path: '/pool-service-palm-beach-gardens'
      fullPath: '/pool-service-palm-beach-gardens'
      preLoaderRoute: typeof PoolServicePalmBeachGardensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-gardens-pool-service': {
      id: '/contact-gardens-pool-service'
      path: '/contact-gardens-pool-service'
      fullPath: '/contact-gardens-pool-service'
      preLoaderRoute: typeof ContactGardensPoolServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-gardens-pool-service': {
      id: '/about-gardens-pool-service'
      path: '/about-gardens-pool-service'
      fullPath: '/about-gardens-pool-service'
      preLoaderRoute: typeof AboutGardensPoolServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof CategoryRoute
    }
  }
}

interface CategoryRouteChildren {
  CategorySlugRoute: typeof CategorySlugRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategorySlugRoute: CategorySlugRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  AboutGardensPoolServiceRoute: AboutGardensPoolServiceRoute,
  AuthorRoute: AuthorRoute,
  ContactGardensPoolServiceRoute: ContactGardensPoolServiceRoute,
  PoolServicePalmBeachGardensRoute: PoolServicePalmBeachGardensRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  TagTagRoute: TagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
